### PR TITLE
Library branch

### PR DESCRIPTION
**Pull request by epmikida**
Not ready for merge yet

---
This change is [Reviewable](https://reviewable.io/reviews/charmworks/exam2m/22)

### CODE REVIEW

**Comment by epmikida** [comment]
This finally passes all tests and is ready for review and merge.

At some point later, we should probably have a more in depth discussion on exactly what the API should look like. There were a few decisions I made somewhat arbitrarily, and some things could probably be better designed. But it shouldn't be hard to change, and this gets us to a point where we can easily modify and test the API all within ExaM2M itself.

**Review by jbakosi — CHANGES_REQUESTED** [review]
I will pull this, build within exam2m using clang/gnu/intel, might push some warning fixes, and will also pull into quinoa and continue from there. Looks good, I have a few minor questions before merge. Thanks.

> Reviewed 12 of 31 files at r1, 11 of 17 files at r2, 12 of 12 files at r3, 1 of 1 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/charmworks/exam2m/22#-:-MO2EP_z4UoenRMwxQIk:b-x19d06)* status: all files reviewed, 5 unresolved discussions (waiting on @epmikida and @nitbhat)

___
*[src/Main/ExaM2M.cpp, line 110 at r5](https://reviewable.io/reviews/charmworks/exam2m/22#-MO2BACfC-gONbv-fN6Y:-MO2BACfC-gONbv-fN6Z:bkovbfl) ([raw file](https://github.com/charmworks/exam2m/blob/9c1655fa7ca0e9f1523da364f2497c057dfb6fdf/src/Main/ExaM2M.cpp#L110)):*
> ```cpp
>     void quiescence() {
>       try {
>         CkAbort("Queiscence detected before tranfser completed\n");
> ```

"Quiescence detected before transfer completed"
___
*[src/Main/MeshArray.cpp, line 84 at r5](https://reviewable.io/reviews/charmworks/exam2m/22#-MO2BsiR8ck5XVWut-8o:-MO2BsiR8ck5XVWut-8p:bfvemub) ([raw file](https://github.com/charmworks/exam2m/blob/9c1655fa7ca0e9f1523da364f2497c057dfb6fdf/src/Main/MeshArray.cpp#L84)):*
> ```cpp
> 
>   // Tell the RTS that the MeshArray chares have been created and compute
>   // the total number of mesh points across whole problem
> ```

I guess this comment is now out of sync because we do not sum the total number of mesh points with this contribute.
___
*[src/Transfer/Worker.hpp, line 100 at r5](https://reviewable.io/reviews/charmworks/exam2m/22#-MO2Dg64Cfq7GyxIe3li:-MO2Dg64Cfq7GyxIe3lj:bmugegk) ([raw file](https://github.com/charmworks/exam2m/blob/9c1655fa7ca0e9f1523da364f2497c057dfb6fdf/src/Transfer/Worker.hpp#L100)):*
> ```cpp
>     std::vector< std::size_t >* m_inpoel;
>     //! Pointer to point coordinates
>     tk::UnsMesh::Coords* m_coord;
> ```

I'm always afraid of holding pointers in chare arrays that may migrate. Is this going to be okay with LB?
___
*[src/Transfer/Worker.cpp, line 275 at r5](https://reviewable.io/reviews/charmworks/exam2m/22#-MO2E6p7-ImB1yHCKio3:-MO2E6p7-ImB1yHCKio4:bu1pmar) ([raw file](https://github.com/charmworks/exam2m/blob/9c1655fa7ca0e9f1523da364f2497c057dfb6fdf/src/Transfer/Worker.cpp#L275)):*
> ```cpp
> 
>   // TODO: What if we get multiple solns for the same point (For example when a
>   // point in the dest exactly coincides with a point in the source)
> ```

In that case the solution should also be the same, because the solution of the PDE should be the same in the same physical location.
___
*[src/Main/Driver.hpp, line 42 at r5](https://reviewable.io/reviews/charmworks/exam2m/22#-MO28eHH5yU6QckNeRgy:-MO28eHH5yU6QckNeRgz:bpotmie) ([raw file](https://github.com/charmworks/exam2m/blob/9c1655fa7ca0e9f1523da364f2497c057dfb6fdf/src/Main/Driver.hpp#L42)):*
> ```cpp
>   public:
>     //! Constructor
>     explicit Driver();
> ```

Since the body of the ctor is empty, we could probably just do
```cpp
explicit Driver() = default;
```
and remove the .cpp.
___
*[src/Main/Driver.hpp, line 57 at r5](https://reviewable.io/reviews/charmworks/exam2m/22#-MO28TNM9hpfmKmr9bSh:-MO28TNM9hpfmKmr9bSi:b-poq4up) ([raw file](https://github.com/charmworks/exam2m/blob/9c1655fa7ca0e9f1523da364f2497c057dfb6fdf/src/Main/Driver.hpp#L57)):*
> ```cpp
>       p | m_sourcemeshid;
>       p | m_destmeshid;
>     }
> ```

We should also pup `m_timer`.

**Comment by epmikida** [comment]
@jbakosi I believe I addressed all of your above comments except 2. The driver ctor is no longer the default with the addition of iterations, at least for now.

As for your question about pointers, those pointers are currently safe as long as you don't migrate DURING the transfer, which I think is a reasonable restriction to have. But there are two ways we can address your concern. The first is what we do now, just have the restriction that LB / migration cannot occur in the middle of a transfer. We can add some errors to detect this as well so if we try to migrate, we will at least see the error for why things fail.

The second would be to split the API slightly, and have the user responsible for syncing migrations. These pointers are pointers to application side mesh data. That data presumably is already being pupped by the application at migration time. All the application would have to do in addition to unpacking it's own data is to also re-set the pointers by calling `setDestPoints`/`setSourceTets` in pup when unpacking. The only issue with that right now is the current API also starts the transfer when you call setDestPoints and setSourceTets, so we'd want to split it into two separate calls. Something like `set...()` and `doTransfer` for example.

Personally I think option one is the way to go for simplicity. But we can discuss more when we finalize the API.

**Comment by epmikida** [comment]
Whoops. Forgot to push. NOW I've addressed your comments.

**Comment by jbakosi** [comment]
Okay, sounds good, thanks for the explanation. As long as you/we have a good handle on what happens with migration, we should be good.

**Review by jbakosi — APPROVED** [review]
> Reviewed 4 of 6 files at r7, 2 of 2 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/charmworks/exam2m/22)* status: all files reviewed, 1 unresolved discussion (waiting on @epmikida and @nitbhat)

**Pull request merged**
