### PR TITLE
Quiescence

### PR DESCRIPTION
**Pull request by jbakosi**
This ports over a function from Quinoa so a debug build succeeds and triggers a nonzero exit code if quiescence is detected. (Saw that by looking at the CI logs @nitbhat put in.)

@nitbhat: Can you please put in a debug build to the CI as well?

---
This change is [Reviewable](https://reviewable.io/reviews/charmworks/exam2m/5)

### CODE REVIEW

**Comment by nitbhat** [comment]
Yes, I'll add a debug build to CI. 

The change looks good and a debug build succeeds now. However, @jbakosi, what's the reasoning behind throwing a nonzero exit code if quiescence is detected? (since this will cause tests to fail as this one: https://github.com/Charmworks/ExaM2M/pull/5/checks?check_run_id=954884530)

**Comment by jbakosi** [comment]
The quiescence detection is there as a way to detect asynchronous-logic problems. Currently it is triggered, because there is such a problem - unless it is a false positive. Either case, we need to investigate this before this can be merged. But I wanted to enable it so it fails.

Thanks for adding a debug build.

**Comment by nitbhat** [comment]
> The quiescence detection is there as a way to detect asynchronous-logic problems. Currently it is triggered, because there is such a problem - unless it is a false positive. Either case, we need to investigate this before this can be merged. But I wanted to enable it so it fails.

Oh okay, I see, that makes sense. I misunderstood it to be the natural way to exit. (I am yet to deeply dig into the code myself and understand it entirely). 

> 
> Thanks for adding a debug build.

Of course! You're very welcome.

**Comment by epmikida** [comment]
> The quiescence detection is there as a way to detect asynchronous-logic problems. Currently it is triggered, because there is such a problem - unless it is a false positive. Either case, we need to investigate this before this can be merged. But I wanted to enable it so it fails.
> 
> Thanks for adding a debug build.

Just one other thing to point out. The QD check only really works when there is not other QD for application synchronization and the application has a clear path to a clean exit. For Quinoa that worked well. IIRC for ExaM2M, right now there might be QD used to synchronize certain parts of the code, and possibly even for detecting a clean exit. We'd also have to see how QD interacts with the collision detection library.

**Comment by jbakosi** [comment]
> Just one other thing to point out. The QD check only really works when there is not other QD for application synchronization and the application has a clear path to a clean exit. For Quinoa that worked well. IIRC for ExaM2M, right now there might be QD used to synchronize certain parts of the code, and possibly even for detecting a clean exit. We'd also have to see how QD interacts with the collision detection library.

Uh, okay, I was not aware that QD might be used other than detecting a problem. In that case, of course, we should not throw as this PR suggests.

**Comment by epmikida** [comment]
> > Just one other thing to point out. The QD check only really works when there is not other QD for application synchronization and the application has a clear path to a clean exit. For Quinoa that worked well. IIRC for ExaM2M, right now there might be QD used to synchronize certain parts of the code, and possibly even for detecting a clean exit. We'd also have to see how QD interacts with the collision detection library.
> 
> Uh, okay, I was not aware that QD might be used other than detecting a problem. In that case, of course, we should not throw as this PR suggests.

It still might be totally fine to do. We just can't do it blindly and assume it will work. Or some of the synchronization in the code will need to be modified. Just wanted to point out why it could cause false failures if we just stick it in without looking at the surrounding code.

**Comment by nitbhat** [comment]
> > > Just one other thing to point out. The QD check only really works when there is not other QD for application synchronization and the application has a clear path to a clean exit. For Quinoa that worked well. IIRC for ExaM2M, right now there might be QD used to synchronize certain parts of the code, and possibly even for detecting a clean exit. We'd also have to see how QD interacts with the collision detection library.
> > 
> > 
> > Uh, okay, I was not aware that QD might be used other than detecting a problem. In that case, of course, we should not throw as this PR suggests.
> 
> It still might be totally fine to do. We just can't do it blindly and assume it will work. Or some of the synchronization in the code will need to be modified. Just wanted to point out why it could cause false failures if we just stick it in without looking at the surrounding code.

The first commit looks good. 

As of now, since we use QD only for exiting, shall I go ahead and remove the throw? As the code evolves, if we bring in another mechanism to cleanly exit (maybe a reduction or so), we can bring back this throw.

**Comment by jbakosi** [comment]
> As of now, since we use QD only for exiting, shall I go ahead and remove the throw? As the code evolves, if we bring in another mechanism to cleanly exit (maybe a reduction or so), we can bring back this throw.

Sounds good to me.

**Review by nitbhat — APPROVED** [review]

**Pull request merged**
