### PR TITLE
Ensure that duplicate points are not sent for collision detection

### PR DESCRIPTION
**Pull request by epmikida**
For vertices on the boundaries, multiple chares have these vertices
in their mesh data. This change designates the chare with the lowest
index as the owner of these points and ensures that it is the only
chare sending them to collision detection.

---
This change is [Reviewable](https://reviewable.io/reviews/charmworks/exam2m/15)

### CODE REVIEW

**Review by jbakosi — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/charmworks/exam2m/15)* status: all files reviewed, 1 unresolved discussion (waiting on @epmikida and @nitbhat)

___
*[src/Transfer/Worker.cpp, line 154 at r1](https://reviewable.io/reviews/charmworks/exam2m/15#-MI0oPg93X764xI6jE7X:-MI0oPgAEEH-T9G7XvN4:bm8x6a2) ([raw file](https://github.com/charmworks/exam2m/blob/666e86763caf5f082f197095caaca71da72980a6/src/Transfer/Worker.cpp#L154)):*
> ```cpp
>     prio[nBoxes] = m_firstchunk;
>     nBoxes++;
>   }
> ```

Maybe:
```
  const auto nVertices = m_coord[0].size();
  std::vector< bbox3d > boxes( nVertices );
  std::vector< int > prio( nVertices );
  int nBoxes = 0;
  for (int i = 0; i < nVertices; i++)
    if (owner(i)) {
      boxes[nBoxes].empty();
      boxes[nBoxes].add(CkVector3d(m_coord[0][i], m_coord[1][i], m_coord[2][i]));
      prio[nBoxes] = m_firstchunk;
      ++nBoxes;
    }
```

**Comment by epmikida** [comment]
@nitbhat is going to look into fixing this patch. The issue we ran into is that once you start skipping points, the bbox index you give to the CD library no longer matches the index of the destination chare's vertices, so solutions don't end up in the right place. A simple vector to map bbox index to dest vertex index should solve the issue.

**Comment by nitbhat** [comment]
The third test is failing with this error:

```
3: [fv-az58:70675] 1 more process has sent help message help-mpi-btl-base.txt / btl:no-nics
3: [fv-az58:70675] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
3: -- Binary diff found match for 'sphere2box_pe2.src.std.exo.0' in 'out.0.e-s.0.2.0'
3: -- Binary diff found match for 'sphere2box_pe2.src.std.exo.1' in 'out.0.e-s.0.2.1'
3: -- Binary diff found match for 'sphere2box_pe2.dst.std.exo.0' in 'out.1.e-s.0.2.0'
3: CMake Error at /home/runner/work/ExaM2M/ExaM2M/cmake/test_runner.cmake:373 (message):
3:   Binary diff command failed:
3:   /home/runner/work/ExaM2M/ExaM2M/external/install/gnu-x86_64/bin/exodiff -q
3:   -f exodiff.cfg sphere2box_pe2.dst.std.exo.1 out.1.e-s.0.2.1, error: 2
3: 
3: 
Errors while running CTest
3/3 Test #3: sphere2box_pe2 ...................***Failed  Error regular expression found in output. Regex=[CMake Error]  4.08 sec
```

I am seeing this locally as well.

**Comment by epmikida** [comment]
> The third test is failing with this error:
> 
> ```
> 3: [fv-az58:70675] 1 more process has sent help message help-mpi-btl-base.txt / btl:no-nics
> 3: [fv-az58:70675] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
> 3: -- Binary diff found match for 'sphere2box_pe2.src.std.exo.0' in 'out.0.e-s.0.2.0'
> 3: -- Binary diff found match for 'sphere2box_pe2.src.std.exo.1' in 'out.0.e-s.0.2.1'
> 3: -- Binary diff found match for 'sphere2box_pe2.dst.std.exo.0' in 'out.1.e-s.0.2.0'
> 3: CMake Error at /home/runner/work/ExaM2M/ExaM2M/cmake/test_runner.cmake:373 (message):
> 3:   Binary diff command failed:
> 3:   /home/runner/work/ExaM2M/ExaM2M/external/install/gnu-x86_64/bin/exodiff -q
> 3:   -f exodiff.cfg sphere2box_pe2.dst.std.exo.1 out.1.e-s.0.2.1, error: 2
> 3: 
> 3: 
> Errors while running CTest
> 3/3 Test #3: sphere2box_pe2 ...................***Failed  Error regular expression found in output. Regex=[CMake Error]  4.08 sec
> ```
> 
> I am seeing this locally as well.

Yes, that is expected at this point. That was the issue with this PR: the indexing is off when you only contribute owned vertices. So we need to add a way to convert from bbox index to vertex index.

**Pull request merged**
